spring:
  application:
    name: bootjarAuth
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    gcp:
      storage:
        credentials:
          location: ${location}
      project-id: ${project-id}
      bucket: ${bucketName}


jwt:
  # kube 할 때 env에 넣어서 실행하기
  secret: ${secret}
  expiration: ${exp}