spring:
  application:
    name: bootjarAuth
  datasource:
    url: jdbc:mysql://bootjar-mysql:3306/bootjar_user
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    gcp:
      storage:
        credentials:
          location: ${location}
      project-id: ${project-id}
      bucket: ${bucketName}
  # mailService
  mail:
    host: smtp.gmail.com
    port: 587 # TLS 사용
    username: ${gmail-id}
    password: ${gmail-pw}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF-8
    default-encoding: UTF-8

jwt:
  secret: ${secret}
  expiration: ${exp}